# This file controls the behaviour of a routine that generates a dataset
# of information rleating to patients who have had acute coronary syndromes
# or PCI procedures. The script generates a dataset where each row is a
# patient, and the columns contain characteristics of the index event
# (either ACS or PCI) and other diagnostic episodes that happened either
# before or after the index event.
#
# output columns:
#  index_spell_date: The date of the spell containing the index episode.
#  index_type: "ACS" or "PCI" depending on the type of index episode
#  age: The age of the patient at the index spell
#  <diagnosis_name>_before: The number of occurances of the diagnosis
#      identified by <diagnosis_name> (a group of ICD codes) in episodes
#      in the period <months_before> before the index event.
#  <diagnosis_name>_after: The number of occurances of the diagnosis
#      identified by <diagnosis_name> (a group of ICD codes) in episodes
#      in the period <months_after> after the index event.
#  bleed_after: The number of bleeding events (defined by a group of ICD
#      codes) in the <months_after> period after the index event.
#  ischaemia_after: The number of ischaemic events (defined by a group
#      of ICD codes) in the <months_after> period after the index event.
#  death_after: Whether the patient died in the following <months_after>
#      period
#  cardiovascular_death: Whether the death was associated with a
#      cardiovascular ICD code (NA if no death_after)
#  ischaemia_death: Whether the death was associated with an ischaemia
#      ICD code (NA if no death_after)
#  
#
#

  


  
