# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_cpp <- function(thing) {
    .Call(`_rdb_test_cpp`, thing)
}

in_mem_test <- function() {
    invisible(.Call(`_rdb_in_mem_test`))
}

make_acs_dataset <- function() {
    invisible(.Call(`_rdb_make_acs_dataset`))
}

