# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_cpp <- function(thing) {
    .Call(`_rdb_test_cpp`, thing)
}

make_acs_dataset <- function(config_path_chr) {
    invisible(.Call(`_rdb_make_acs_dataset`, config_path_chr))
}

test_random_code <- function() {
    invisible(.Call(`_rdb_test_random_code`))
}

debug_sql <- function(dsn_character, query_character) {
    invisible(.Call(`_rdb_debug_sql`, dsn_character, query_character))
}

parse_code <- function(file, code, what) {
    .Call(`_rdb_parse_code`, file, code, what)
}

dump_groups <- function(file) {
    .Call(`_rdb_dump_groups`, file)
}

