on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: true
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install linux system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt install unixodbc-dev libyaml-cpp-dev

      # Use g++ to avoid c++20 build problems.
      # As per https://github.com/Homebrew/homebrew-core/issues/95561
      # it is necessary to specify the include path to
      # brew installed libraries. Added a hardcoded path to unixodbc
      # because the pkg-config version doesn't work -- need to find
      # some way to discover the version number
      - name: Install mac system dependencies
        if: runner.os == 'macOS'
        run: |
          brew install gcc unixodbc yaml-cpp
          mkdir ~/.R
          export YAML_FLAGS=$(pkg-config --cflags --libs yaml-cpp)
          export UNIXODBC_FLAGS="-I/usr/local/Cellar/unixodbc/2.3.11/include -L/usr/local/Cellar/unixodbc/2.3.11/lib"
          cat > ~/.R/Makevars << EOF
          CC=gcc-13
          CXX=g++-13
          CXX20=g++-13
          CXX20FLAGS=$YAML_FLAGS $UNIXODBC_FLAGS
          EOF
          
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
